### ISSUE TITLE
图片检索比对原理

### ISSUE THREAD

**Issue by lonngxiang** [SongKaixiang/image_retrieval_platform#1]
麻烦咨询下您这图片比对检索相识度是怎么算的吗？我看sortimg里直接相乘，这是什么原理呢

**Comment by lonngxiang** [comment]
另外load_model调用预训练模型，add_block += [nn.Linear(num_ftrs, 30)] ，30个分类结果这是表示什么意思呢，为什么是30？

**Comment by skx6** [comment]
是这样的，每张图都计算了一个对应的向量，通过向量之间的相似性衡量两张图之间的相似性。这里采用的是余弦相似度，计算方法是向量点积除以向量模的乘积，因为向量已经被归一化，所以用向量点积代表相似度。

网络最后一层全连接层实际上是被去掉的，使用2048维的编码代表原始图像。
