### ISSUE TITLE
Great Job!

### ISSUE THREAD

**Issue by AliAsafPolat** [SongKaixiang/image_retrieval_platform#3]
Congratulations very good job. I appriciate it ! Best Regards...

**Comment by AliAsafPolat** [comment]
Which model did you use? Did you trained this model by yourself ?

**Comment by SongKaixiang** [comment]
Thanks a lot, this is a pretrained model of ResNet on ImageNet, which is integrated in pytorch already.

**Comment by skx6** [comment]
> 
> 
> Which model did you use? Did you trained this model by yourself ?

Thanks a lot, this is a pretrained model of ResNet on ImageNet, which is integrated in pytorch already.
